-- CreateEnum
CREATE TYPE "Class" AS ENUM ('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'PREPOSITION', 'CONJUNCTION', 'INTERJECTION');

-- AlterTable
ALTER TABLE "Word" ADD COLUMN     "class" "Class" NOT NULL DEFAULT 'VERB';
